### ISSUE TITLE
[QUESTION] How to pass CropTarget to chrome extension service worker? 

### ISSUE THREAD

**Issue by wlevchenko** [w3c/mediacapture-region#75]
I am trying to receive cropTarget from the content script in the service worker. (Chrome extension)

```
async function getCropTarget () {
  const element = document.getElementById('crop-area')
  const cropTarget = await window.CropTarget.fromElement(element)

  return cropTarget
}
(async () => {
  const tabId = await getTabId()
  if (tabId != null) {
    chrome.scripting
      .executeScript({
        target: { tabId },
        func: getCropTarget
      })
      .then(injectionResults => {
        console.log(injectionResults)
      })
  }
})()
```

But I just received a blank object.
![image](https://user-images.githubusercontent.com/38959370/218342895-92b9c2a9-aeec-4f44-b371-e645b88ea620.png)

Do I have any chance to do this?
I assume that is not possible because CropTarget is not a JSON-ifiable object.
Am I right?

**Comment by youennf** [comment]
CropTarget should be available in all regular workers (dedicated, shared, and service).
Chrome extensions are different from all of these and are not really defined here.
It might be best to file an issue in chrome tracker.

**Comment by wlevchenko** [comment]
> CropTarget should be available in all regular workers (dedicated, shared, and service). Chrome extensions are different from all of these and are not really defined here. It might be best to file an issue in chrome tracker.

got it, thanks

**Comment by beaufortfrancois** [comment]
For the record, my understanding is that messages passed between browser extension contexts (content script and service workers) must be "JSON-ifiable" objects ([source](https://developer.chrome.com/docs/extensions/reference/runtime/#method-sendMessage)).

Even though CropTarget is [serializable](https://w3c.github.io/mediacapture-region/#crop-target), it's not enough to get it to work in browser extensions.

I think this is one more use case for https://github.com/w3c/mediacapture-region/issues/46 which proposes to use a unique identifier instead of an opaque wrapper.

**Comment by eladalon1983** [comment]
@wlevchenko, if you do file bugs on this topic in the Chromium repo, please feel free to assign to me. In this case, though, based on @beaufortfrancois's research, it sounds like it **is** actually a spec issue. Your contributions on #46 would be welcome. (It's a long thread; I think it's reasonable to mention your use-case even without reading it thoroughly.)
